---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangy.
--- DateTime: 2023/7/10 9:52
---

-- 先找找有没有这个限流对象的设置
local key = KEYS[1]
local expiration = ARGV[1]
local maxCnt = tonumber(ARGV[2])
local val = redis.call('get', key)

if val == false then
    if maxCnt < 1 then
        -- 执行限流
        return "true"
    else
        -- set your_service 1 px 100s
        redis.call('set', key, 1, 'PX', expiration)
        -- 不执行限流
        return "false"
    end
elseif tonumber(val) < maxCnt then
    -- 有这个限流对象，但是还没到阈值
    redis.call('incr', key)
    -- 不指定限流
    return "false"
else
    -- 执行限流
    return "true"
end